#!/usr/bin/env python3
"""Generate src/imx582_modes.h from the vendor IMX582 mode tables.

The generated header gives the kernel driver one register table plus one
descriptor per sensor mode, so VIDIOC_S_FMT / VIDIOC_S_PARM can switch the
sensor between the recording formats instead of needing a module reload with
different exp_hsize/exp_vsize parameters.

Usage:  python scripts/gen_modes_header.py [src/rubensimx582_Sensor.h] [out.h]

The vendor table's own VTS is what the vendor driver used.  For preview we
write a shorter VTS than the table (3300 instead of 3658) because that is the
configuration the K50 port was measured and verified with: it buys ~33 fps at
4000x3000 without changing the readout mode.  Every other mode keeps the
table's VTS, which is the mode's nominal frame rate.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from parse_modes import parse_tables, val, pair16  # noqa: E402

# mode table name -> (driver name, VTS the driver writes, comment)
SUPPORTED = {
    "preview":       ("preview",      3300, "4000x3000 2x2 binned, VTS shortened from the table's 3658"),
    "normal_video":  ("normal_video", 0,    "4000x2256 16:9, table VTS"),
    "custom3":       ("custom3",      0,    "4000x2256 at 60 fps, table VTS"),
    "custom2":       ("custom2",      0,    "1920x1080 at 120 fps, table VTS"),
    "hs_video":      ("hs_video",     0,    "1920x1080 at 240 fps, table VTS"),
}

# deliberately not exposed: custom4 is 8000x6000 (60 MB per frame, three times
# the CMA pool) and custom5 is a non-binned 4-cell readout whose CFA layout the
# converter does not handle yet.  Both can still be brought up by hand with the
# exp_hsize/exp_vsize module parameters.
EXCLUDED = {"custom4", "custom5"}

# The receiver's timing follows the sensor's link rate.  These are the vendor
# constants from isp71_ref (mtk_cam-seninf-hw_phy_3_0.c) that port2_rx71.py
# re-implements; the driver recomputes the same two values on a mode switch.
SENINF_CK = 273000000
DPHY_TRAIL_DT = 68


def rx_params(mbps):
    """(DMY_CYCLE, HS_TRAIL) for a MIPI data rate in Mbps per lane."""
    if not mbps:
        return 0, 0
    data_rate = mbps * 1000000
    cycles = 64 * SENINF_CK // data_rate + 1
    ui_224 = 224 * 1000 // mbps
    if ui_224 <= DPHY_TRAIL_DT:
        return cycles, 0
    t = (ui_224 - DPHY_TRAIL_DT) * SENINF_CK
    return cycles, t // 1000000000 + (1 if t % 1000000000 else 0)


def main():
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "src/rubensimx582_Sensor.h")
    out = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else "src/imx582_modes.h")
    # the vendor header names them rubensimx582_<mode>_setting
    tables = {}
    for name, pairs in parse_tables(src):
        key = name
        if key.startswith("rubensimx582_"):
            key = key[len("rubensimx582_"):]
        if key.endswith("_setting"):
            key = key[:-len("_setting")]
        tables[key] = pairs

    missing = [t for t in SUPPORTED if t not in tables]
    if missing:
        raise SystemExit(f"mode tables missing from {src}: {', '.join(missing)}")
    entries = []
    for table, (name, vts_override, comment) in SUPPORTED.items():
        pairs = tables[table]
        hts = pair16(pairs, 0x0342, 0x0343)
        vts = pair16(pairs, 0x0340, 0x0341)
        ow = pair16(pairs, 0x034C, 0x034D)
        oh = pair16(pairs, 0x034E, 0x034F)
        # 0x030e/0x030f is the MIPI data rate in Mbps per lane (0x055a = 1370,
        # which is what port2_rx71.py's D-PHY timing is computed from).
        mipi_mbps = pair16(pairs, 0x030e, 0x030f)
        pllcode = pair16(pairs, 0x0306, 0x0307)
        pclk = 4.8e6 * pllcode if pllcode else 0
        run_vts = vts_override or vts
        fps = pclk / (hts * run_vts) if pclk and hts and run_vts else 0
        entries.append({
            "table": table, "name": name, "pairs": pairs, "vts": run_vts,
            "vts_table": vts, "hts": hts, "ow": ow, "oh": oh,
            "pclk_khz": round(pclk / 1e3), "fps_x100": round(fps * 100),
            "bin": val(pairs, 0x0900), "exp_max": run_vts - 128,
            "mipi_mbps": mipi_mbps,
            "comment": comment,
        })

    init_pairs = tables.get("init")
    if not init_pairs:
        raise SystemExit("init_setting table not found")

    lines = []
    w = lines.append
    w("/* SPDX-License-Identifier: GPL-2.0 */")
    w("/*")
    w(" * IMX582 (rubens) sensor mode tables for the CAMSV capture driver.")
    w(" *")
    w(" * Generated by scripts/gen_modes_header.py from the vendor header")
    w(f" * {src.as_posix()} (MiCode/Xiaomi_Kernel_OpenSource,")
    w(" * rubens-s-oss).  One table per mode: the driver replays it over I2C when")
    w(" * an application asks for another frame size through VIDIOC_S_FMT,")
    w(" * VIDIOC_S_PARM or the matching /proc/camcap command, so the recording")
    w(" * formats of the sensor are selectable without reloading the module.")
    w(" *")
    w(" * Do not edit by hand.")
    w(" */")
    w("#ifndef CAMCAP_IMX582_MODES_H")
    w("#define CAMCAP_IMX582_MODES_H")
    w("")
    w("struct cam_mode_reg {")
    w("\tunsigned short reg;")
    w("\tunsigned short val;")
    w("};")
    w("")
    w("struct cam_sensor_mode {")
    w("\tconst char *name;")
    w("\tconst struct cam_mode_reg *regs;")
    w("\tunsigned int nregs;")
    w("\tunsigned int hsize;\t/* 0x034C/0x034D output window */")
    w("\tunsigned int vsize;\t/* 0x034E/0x034F output window */")
    w("\tunsigned int hts;")
    w("\tunsigned int vts;\t/* what the driver writes */")
    w("\tunsigned int vts_table;\t/* what the vendor table contains */")
    w("\tunsigned int mipi_mbps;\t/* 0x030e/0x030f: Mbps per lane */")
    w("\tunsigned int pclk_khz;")
    w("\tunsigned int fps_x100;")
    w("\tunsigned int sensor_bin;\t/* vendor 0x0900: 1 = 2x2 on-sensor binning */")
    w("\tunsigned int exp_max;\t/* vts - 128 */")
    w("\tconst char *comment;")
    w("};")
    w("")
    w("/* power-on configuration, replayed before a mode table */")
    w("static const struct cam_mode_reg cam_imx582_tbl_init[] = {")
    for i in range(0, len(init_pairs), 6):
        chunk = init_pairs[i:i + 6]
        w("\t" + " ".join("{ 0x%04x, 0x%02x }," % (r, v) for r, v in chunk))
    w("};")
    w("")
    w(f"#define CAMCAP_IMX582_INIT_NREGS {len(init_pairs)}")
    w("")
    for e in entries:
        w(f"/* {e['name']}: {e['comment']} */")
        w(f"static const struct cam_mode_reg cam_imx582_tbl_{e['name']}[] = {{")
        for i in range(0, len(e["pairs"]), 6):
            chunk = e["pairs"][i:i + 6]
            w("\t" + " ".join("{ 0x%04x, 0x%02x }," % (r, v) for r, v in chunk))
        w("};")
        w("")
    w("static const struct cam_sensor_mode cam_imx582_modes[] = {")
    for e in entries:
        w("\t{")
        w(f"\t\t.name = \"{e['name']}\",")
        w(f"\t\t.regs = cam_imx582_tbl_{e['name']},")
        w(f"\t\t.nregs = {len(e['pairs'])},")
        w(f"\t\t.hsize = {e['ow']}, .vsize = {e['oh']},")
        w(f"\t\t.hts = {e['hts']}, .vts = {e['vts']}, .vts_table = {e['vts_table']},")
        w(f"\t\t.mipi_mbps = {e['mipi_mbps']},")
        w(f"\t\t.pclk_khz = {e['pclk_khz']}, .fps_x100 = {e['fps_x100']},")
        w(f"\t\t.sensor_bin = {e['bin']}, .exp_max = {e['exp_max']},")
        w(f"\t\t.comment = \"{e['comment']}\",")
        w("\t},")
    w("};")
    w("")
    w(f"#define CAMCAP_IMX582_NMODES {len(entries)}")
    w("")
    w("/* largest single raw frame over the modes above, in bytes */")
    biggest = max(int(e["ow"] * 3 / 2) * e["oh"] for e in entries)
    w(f"#define CAMCAP_IMX582_MAX_FRAME {biggest}")
    w("")
    w("#endif /* CAMCAP_IMX582_MODES_H */")
    w("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({out.stat().st_size} bytes, {len(entries)} modes)")
    for e in entries:
        cyc, trail = rx_params(e["mipi_mbps"])
        print(f"  {e['name']:14s} {e['ow']}x{e['oh']}  HTS {e['hts']} VTS {e['vts']}"
              f" (table {e['vts_table']})  pclk {e['pclk_khz']} kHz"
              f"  {e['fps_x100'] / 100:.2f} fps  bin {e['bin']}"
              f"  exp_max {e['exp_max']}  stride {e['ow'] * 3 // 2}"
              f"  mipi {e['mipi_mbps']} Mbps (cycle {cyc}, hs_trail {trail})")
    if EXCLUDED:
        print(f"  excluded: {', '.join(sorted(EXCLUDED))} (see the header comment)")


if __name__ == "__main__":
    main()
